### PR TITLE
KEYCLOAK-17330 Update to latest stable keycloak-init container

### LINKED ISSUE #478: Update to latest stable keycloak-init container
### Describe the bug

The keycloak-init-container image is currently pinned to the "master"
shared tag, which has not been updated for two years.

This commit updates the image tag to use the latest released tag for the
container.

This container comes with a couple of benefits:

* Accurate URL parsing, the Python parsing has issues.
* Ability to use basic auth URLs for extensions.
* Much smaller image size.

### Version

16.1.0

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sathieu**
The keycloak-init-container image is currently pinned to the "master"
shared tag, which has not been updated for two years.

This commit updates the image tag to use the latest released tag for the
container.

This container comes with a couple of benefits:

* Accurate URL parsing, the Python parsing has issues.
* Ability to use basic auth URLs for extensions.
* Much smaller image size.

Fixes #478

## Additional Information

- Reduce the vulnerabilities from 309 ( 101 High ) to none (https://quay.io/repository/keycloak/keycloak-init-container?tag=latest&tab=tags)
- Allows the use of private extensions via the use of a basic auth URL.

## Checklist:
- [ ] Automated Tests
- [x] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by kfox1111** [comment]
should the image not be versioned? latest/master is generally not a best practice.

**Comment by sathieu** [comment]
@kfox1111 This is the same as the keycloak image (`DefaultKeycloakImage  = "quay.io/keycloak/keycloak:latest"`). It's updated when the release is done, in `set-version.sh`.

**Comment by kfox1111** [comment]
Ah. ok. Thanks.

**Comment by sathieu** [comment]
> Reduce the vulnerabilities from 309 ( 101 High ) to none

🙋  @slaskawi, @vmuzikar @jonathanvila  This PR fixes a lot of vulnerabilities. I think this deserve a fast path.

NB : I have [another PR](https://github.com/keycloak/keycloak-operator/pull/398) to review too.

**Comment by sathieu** [comment]
@vmuzikar I just rebased, fixed conflicts and force-pushed. Please review :pray:.

File: set-version.sh [hunk 1]
```diff
@@ -15,3 +15,4 @@ function replace_value_in_file() {
 replace_value_in_file ".*Version = " "$1" "version/version.go" "\""
 replace_value_in_file ".*DefaultKeycloakImage.*= " "quay.io\/keycloak\/keycloak:$1-legacy" "pkg/model/image_manager.go" "\""
 replace_value_in_file ".*image: " "quay.io\/keycloak\/keycloak-operator:$1" "deploy/operator.yaml"
+replace_value_in_file ".*DefaultKeycloakInitContainer.*= " "quay.io\/keycloak\/keycloak-init-container:$1" "pkg/model/image_manager.go" "\""
```
Comment (vmuzikar) [inline set-version.sh:18]: I need to double check with @stianst whether the init container will have `-legacy` suffix in the next Keycloak release.

**Review by vmuzikar — COMMENTED** [review]
@sathieu Thank you for your contribution and sorry for late response. Changes LGTM. I just need to double check init image coordinates for the next KC release.

**Review by vmuzikar — DISMISSED** [review]

**Review by vmuzikar — APPROVED** [review]

**Comment by vmuzikar** [comment]
@sathieu Thanks again for your contribution. I did a small change in your PR to reflect the `-legacy` suffix in the next KC release.

**Comment by sathieu** [comment]
Thanks @vmuzikar!
